/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FactionSymbol } from '../models/FactionSymbol.ts';
import { FactionTrait } from '../models/FactionTrait.ts';
import { HttpFile } from '../http/http.ts';

/**
* Faction details.
*/
export class Faction {
    'symbol': FactionSymbol;
    /**
    * Name of the faction.
    */
    'name': string;
    /**
    * Description of the faction.
    */
    'description': string;
    /**
    * The waypoint in which the faction\'s HQ is located in.
    */
    'headquarters': string;
    /**
    * List of traits that define this faction.
    */
    'traits': Array<FactionTrait>;
    /**
    * Whether or not the faction is currently recruiting new agents.
    */
    'isRecruiting': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "symbol",
            "baseName": "symbol",
            "type": "FactionSymbol",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "headquarters",
            "baseName": "headquarters",
            "type": "string",
            "format": ""
        },
        {
            "name": "traits",
            "baseName": "traits",
            "type": "Array<FactionTrait>",
            "format": ""
        },
        {
            "name": "isRecruiting",
            "baseName": "isRecruiting",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Faction.attributeTypeMap;
    }

    public constructor() {
    }
}



