/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Agent } from '../models/Agent.ts';
import { Cooldown } from '../models/Cooldown.ts';
import { MarketTransaction } from '../models/MarketTransaction.ts';
import { ShipNav } from '../models/ShipNav.ts';
import { HttpFile } from '../http/http.ts';

export class JumpShip200ResponseData {
    'nav': ShipNav;
    'cooldown': Cooldown;
    'transaction': MarketTransaction;
    'agent': Agent;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nav",
            "baseName": "nav",
            "type": "ShipNav",
            "format": ""
        },
        {
            "name": "cooldown",
            "baseName": "cooldown",
            "type": "Cooldown",
            "format": ""
        },
        {
            "name": "transaction",
            "baseName": "transaction",
            "type": "MarketTransaction",
            "format": ""
        },
        {
            "name": "agent",
            "baseName": "agent",
            "type": "Agent",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return JumpShip200ResponseData.attributeTypeMap;
    }

    public constructor() {
    }
}

