/**
 * SpaceTraders API
 * SpaceTraders is an open-universe game and learning platform that offers a set of HTTP endpoints to control a fleet of ships and explore a multiplayer universe.  The API is documented using [OpenAPI](https://github.com/SpaceTradersAPI/api-docs). You can send your first request right here in your browser to check the status of the game server.  ```json http {   \"method\": \"GET\",   \"url\": \"https://api.spacetraders.io/v2\", } ```  Unlike a traditional game, SpaceTraders does not have a first-party client or app to play the game. Instead, you can use the API to build your own client, write a script to automate your ships, or try an app built by the community.  We have a [Discord channel](https://discord.com/invite/jh6zurdWk5) where you can share your projects, ask questions, and get help from other players.   
 *
 * OpenAPI spec version: 2.0.0
 * Contact: joel@spacetraders.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class RefuelShipRequest {
    /**
    * The amount of fuel to fill in the ship\'s tanks. When not specified, the ship will be refueled to its maximum fuel capacity. If the amount specified is greater than the ship\'s remaining capacity, the ship will only be refueled to its maximum fuel capacity. The amount specified is not in market units but in ship fuel units.
    */
    'units'?: number;
    /**
    * Wether to use the FUEL thats in your cargo or not. Default: false
    */
    'fromCargo'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "units",
            "baseName": "units",
            "type": "number",
            "format": ""
        },
        {
            "name": "fromCargo",
            "baseName": "fromCargo",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RefuelShipRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

